name: The Agile Artist
favicon: null
layout_spectrum: 0.5514527221675962
typography_spectrum: 0.9140798393636942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.973706362536177
  lightness: 0.9515401122625917
  saturation: 0.49957037158310413
  rhythmicContrast: 0.28341951710172
purpose: []
